-- Database: hotel_reservation NO CORRER ESTE SCRIPT UNA VEZ ESTE EN LÍNEA EL BACKEND
create table amenity (amenity_id bigint not null auto_increment, icon varchar(255), name varchar(255), primary key (amenity_id)) engine=InnoDB;
create table hotel (check_in_time time(6), check_out_time time(6), stars integer, hotel_id bigint not null auto_increment, address varchar(255), city varchar(255), country varchar(255), description varchar(255), email varchar(255), name varchar(255), phone varchar(255), postal_code varchar(255), primary key (hotel_id)) engine=InnoDB;
create table promotion (discount_percent decimal(38,2), end_date date, max_uses integer, start_date date, hotel_id bigint, promotion_id bigint not null auto_increment, code varchar(255), primary key (promotion_id)) engine=InnoDB;
create table reservation (check_in date, check_out date, discount decimal(38,2), final_price decimal(38,2), total decimal(38,2), created_at datetime(6), guest_id bigint not null, hotel_id bigint not null, reservation_id bigint not null auto_increment, status enum ('CANCELLED','COMPLETED','CONFIRMED','PENDING'), primary key (reservation_id)) engine=InnoDB;
create table reservation_room (final_price decimal(38,2), taxes decimal(38,2), reservation_id bigint not null, room_id bigint not null, primary key (reservation_id, room_id)) engine=InnoDB;
create table review (created_at date, rating integer, guest_id bigint not null, hotel_id bigint not null, review_id bigint not null auto_increment, comment varchar(255), primary key (review_id)) engine=InnoDB;
create table room (base_price decimal(38,2), hotel_id bigint not null, room_id bigint not null auto_increment, room_type_id bigint not null, primary key (room_id)) engine=InnoDB;
create table room_bookings (booking_date date, room_id bigint not null) engine=InnoDB;
create table room_type_amenities (amenity_id bigint not null, room_type_id bigint not null) engine=InnoDB;
create table room_type (max_capacity integer, room_type_id bigint not null auto_increment, description varchar(255), name varchar(255), primary key (room_type_id)) engine=InnoDB;
create table user (birthdate date, blocked bit, user_id bigint not null auto_increment, role varchar(31) not null, email varchar(255), first_name varchar(255), last_name varchar(255), nationality varchar(255), passport_number varchar(255), password_hash varchar(255), phone varchar(255), primary key (user_id)) engine=InnoDB;
alter table amenity add constraint UKtojea3b0gq1a796dt56ml4xdr unique (name);
alter table hotel add constraint UK3p8hpnp751jb9892sxkjmi7bq unique (email);
alter table hotel add constraint UKdcpycvarhghd0g3l6reewmsak unique (name);
alter table promotion add constraint UKlomfalb6gsh66ox4gy0t2g7qw unique (code);
alter table room_type add constraint UKq0y2xl90orh60g19v627mraij unique (name);
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user add constraint UKnxmfpxqo944nspun33yg8nlxb unique (passport_number);
alter table promotion add constraint FKd1a1gx3agdddefq7ioku2b0k1 foreign key (hotel_id) references hotel (hotel_id);
alter table reservation add constraint FKaa0dx3r0k84a9iqffl3me67xa foreign key (guest_id) references user (user_id);
alter table reservation add constraint FKkrmw55mlm5an5ca5qnmrs3pbe foreign key (hotel_id) references hotel (hotel_id);
alter table reservation_room add constraint FK1p8c0gdgl9nnw8g3mavqchw2j foreign key (reservation_id) references reservation (reservation_id);
alter table reservation_room add constraint FKe368pj2d58a8xx37fk8p6k1jl foreign key (room_id) references room (room_id);
alter table review add constraint FKkdprhv0bus71rvfwhw2e7207t foreign key (guest_id) references user (user_id);
alter table review add constraint FKi0ly7ivbh8ijdgoi7cwtuoavt foreign key (hotel_id) references hotel (hotel_id);
alter table room add constraint FKdosq3ww4h9m2osim6o0lugng8 foreign key (hotel_id) references hotel (hotel_id);
alter table room add constraint FKd468eq7j1cbue8mk20qfrj5et foreign key (room_type_id) references room_type (room_type_id);
alter table room_bookings add constraint FKhh1tnb3cjnek9jqsffhfjap90 foreign key (room_id) references room (room_id);
alter table room_type_amenities add constraint FKh5vbc72elhwergmqqnmg9rhfk foreign key (amenity_id) references amenity (amenity_id);
alter table room_type_amenities add constraint FKb4l52p1r38fbjuaopm7nanc3a foreign key (room_type_id) references room_type (room_type_id);


alter table promotion drop foreign key FKd1a1gx3agdddefq7ioku2b0k1;
alter table reservation drop foreign key FKaa0dx3r0k84a9iqffl3me67xa;
alter table reservation drop foreign key FKkrmw55mlm5an5ca5qnmrs3pbe;
alter table reservation_room drop foreign key FK1p8c0gdgl9nnw8g3mavqchw2j;
alter table reservation_room drop foreign key FKe368pj2d58a8xx37fk8p6k1jl;
alter table review drop foreign key FKkdprhv0bus71rvfwhw2e7207t;
alter table review drop foreign key FKi0ly7ivbh8ijdgoi7cwtuoavt;
alter table room drop foreign key FKdosq3ww4h9m2osim6o0lugng8;
alter table room drop foreign key FKd468eq7j1cbue8mk20qfrj5et;
alter table room_bookings drop foreign key FKhh1tnb3cjnek9jqsffhfjap90;
alter table room_type_amenities drop foreign key FKh5vbc72elhwergmqqnmg9rhfk;
alter table room_type_amenities drop foreign key FKb4l52p1r38fbjuaopm7nanc3a;
drop table if exists amenity;
drop table if exists hotel;
drop table if exists promotion;
drop table if exists reservation;
drop table if exists reservation_room;
drop table if exists review;
drop table if exists room;
drop table if exists room_bookings;
drop table if exists room_type_amenities;
drop table if exists room_type;
drop table if exists user;